# Default values are perfect for most servers.  If you want to customize and have a question, look for the answer here first: http://dev.bukkit.org/bukkit-plugins/grief-prevention/pages/setup-and-configuration/
GriefPrevention:
  SeaLevelOverrides:
    survival112: -1
    survival112_nether: -1
    survival112_the_end: -1
    moblottery: -1
    skeeter_nether: -1
    newcity: -1
    elytralobby: -1
    skywarslobby: -1
    parkourmedium: -1
    formuladrift: -1
    speedforce: -1
    fortressofsolitude: -1
    runner: -1
    turfwars: -1
    hurdles: -1
    crossfire: -1
    metropolis: -1
    longparkour: -1
    mazerunner: -1
    spleef: -1
    parkourhub: -1
    towerparkour: -1
    boatrace: -1
    pvpworldsforest: -1
    escaperoom: -1
    hurdles2: -1
    lavahop: -1
    freezetag: -1
    minecraftparkourmode: -1
    elytrapole: -1
    pvpworldsundergroundarmory: -1
    obstaclecourse: -1
    policeoffice: -1
    wooftywoo: -1
    parkoureasy: -1
    vampirez: -1
    superherocity: -1
    hilariousrace: -1
    pvpparkour: -1
    titanstower: -1
    straightlineparkour: -1
    waynemanor: -1
    parkourhard: -1
    colosseumlobby: -1
    garbageworld: -1
    splegg: -1
    torture: -1
    deathrun: -1
    deathmachine: -1
    waterprison: -1
    flyingbattlearena: -1
    sprintparkour: -1
    greenfield_the_end: -1
    rollercoaster: -1
    rules: -1
    office: -1
    parksideprisonescape: -1
    fightclub: -1
    pvpworldsruins: -1
    flyingbattlelobby: -1
    elytraeasy: -1
    gotham: -1
    megaparkour: -1
    info: -1
    godlyparkour: -1
    chess: -1
    hallofjustice: -1
    marathon: -1
    techcombatknockbackgame: -1
    anarchy: -1
    infectiontag: -1
    elytrahard: -1
    verticalparkour: -1
    extremesumo: -1
    newminigamehub: -1
    skeeter_the_end: -1
    checkers: -1
    quickparkour: -1
    flappybirdparkour: -1
    deathdrop: -1
    skywars: -1
    heroicparkour: -1
    lasertag: -1
    initiation: -1
    alpha: -1
    pvpparkourlobby: -1
    infiniteparkour: -1
    turbotowers: -1
    colosseum: -1
    soccer: -1
    greenfield: -1
    spleeflobby: -1
    utopia: -1
    wallenpole: -1
    kingoftheladder: -1
    anarchy_nether: -1
    skeeter: -1
    elytramedium: -1
    elytrapvp: -1
    shortparkour: -1
    plots: -1
    overvoid: -1
    spawn: -1
    powerpicker: -1
    temple: -1
    labyrinth: -1
    pvpworldslobby: -1
    infinitycity: -1
  Claims:
    Mode:
      parkourhub: Survival
      deathrun: Survival
      parkoureasy: Survival
      flyingbattlearena: Survival
      colosseumlobby: Survival
      skeeter_the_end: Disabled
      elytralobby: Survival
      quickparkour: Survival
      fightclub: Survival
      escaperoom: Survival
      office: Survival
      initiation: Survival
      wooftywoo: Survival
      deathmachine: Survival
      pvpparkourlobby: Survival
      pvpparkour: Survival
      megaparkour: Survival
      lasertag: Survival
      wallenpole: Survival
      godlyparkour: Survival
      towerparkour: Survival
      sprintparkour: Survival
      temple: Survival
      flappybirdparkour: Survival
      garbageworld: Survival
      survival112_the_end: Survival
      marathon: Survival
      rules: Survival
      info: Survival
      alpha: Survival
      minecraftparkourmode: Survival
      waynemanor: Survival
      superherocity: Survival
      gotham: Survival
      hallofjustice: Survival
      spawn: Survival
      heroicparkour: Survival
      overvoid: Survival
      runner: Survival
      shortparkour: Survival
      anarchy: Survival
      turbotowers: Survival
      newminigamehub: Survival
      elytramedium: Survival
      flyingbattlelobby: Survival
      skeeter: Survival
      metropolis: Survival
      titanstower: Survival
      utopia: Survival
      parksideprisonescape: Survival
      splegg: Survival
      skeeter_nether: Disabled
      infiniteparkour: Survival
      checkers: Survival
      spleef: Survival
      skywarslobby: Survival
      verticalparkour: Survival
      deathdrop: Survival
      freezetag: Survival
      pvpworldsundergroundarmory: Survival
      formuladrift: Survival
      fortressofsolitude: Survival
      techcombatknockbackgame: Survival
      longparkour: Survival
      straightlineparkour: Survival
      vampirez: Survival
      hurdles2: Survival
      crossfire: Survival
      labyrinth: Survival
      spleeflobby: Survival
      turfwars: Survival
      lavahop: Survival
      greenfield: Survival
      infinitycity: Survival
      chess: Survival
      pvpworldsforest: Survival
      kingoftheladder: Survival
      powerpicker: Survival
      pvpworldslobby: Survival
      policeoffice: Survival
      elytrapole: Survival
      elytraeasy: Survival
      elytrahard: Survival
      newcity: Survival
      speedforce: Survival
      survival112: Survival
      obstaclecourse: Survival
      infectiontag: Survival
      parkourmedium: Survival
      moblottery: Survival
      anarchy_nether: Disabled
      waterprison: Survival
      hurdles: Survival
      parkourhard: Survival
      greenfield_the_end: Disabled
      survival112_nether: Survival
      pvpworldsruins: Survival
      torture: Survival
      extremesumo: Survival
      plots: Survival
      boatrace: Survival
      mazerunner: Survival
      rollercoaster: Survival
      soccer: Survival
      hilariousrace: Survival
      colosseum: Survival
      elytrapvp: Survival
      skywars: Survival
    PreventGlobalMonsterEggs: true
    PreventTheft: true
    ProtectCreatures: true
    PreventButtonsSwitches: true
    LockWoodenDoors: false
    LockTrapDoors: false
    LockFenceGates: true
    EnderPearlsRequireAccessTrust: true
    ProtectHorses: true
    InitialBlocks: 100
    Claim Blocks Accrued Per Hour:
      Default: 100
    Max Accrued Claim Blocks:
      Default: 2000
    Accrued Idle Threshold: 0
    AccruedIdlePercent: 0
    AbandonReturnRatio: 1.0
    AutomaticNewPlayerClaimsRadius: 4
    ExtendIntoGroundDistance: 5
    MinimumWidth: 5
    MinimumArea: 100
    MaximumDepth: 0
    InvestigationTool: STICK
    ModificationTool: GOLD_SPADE
    Expiration:
      ChestClaimDays: 7
      UnusedClaimDays: 14
      AllClaims:
        DaysInactive: 60
        ExceptWhenOwnerHasTotalClaimBlocks: 10000
        ExceptWhenOwnerHasBonusClaimBlocks: 5000
      AutomaticNatureRestoration:
        SurvivalWorlds: false
    AllowTrappedInAdminClaims: false
    MaximumNumberOfClaimsPerPlayer: 0
    CreationRequiresWorldGuardBuildPermission: true
    PortalGenerationRequiresPermission: false
    VillagerTradingRequiresPermission: true
    CommandsRequiringAccessTrust: /sethome
    DeliverManuals: true
    ManualDeliveryDelaySeconds: 30
  Spam:
    Enabled: true
    LoginCooldownSeconds: 60
    LoginLogoutNotificationsPerMinute: 5
    ChatSlashCommands: /me;/global;/local
    WhisperSlashCommands: /tell;/pm;/r;/whisper;/msg
    WarningMessage: Please reduce your noise level.  Spammers will be banned.
    BanOffenders: true
    BanMessage: Banned for spam.
    AllowedIpAddresses: 1.2.3.4; 5.6.7.8
    DeathMessageCooldownSeconds: 120
    Logout Message Delay In Seconds: 0
  PvP:
    RulesEnabledInWorld:
      survival112: true
      survival112_nether: true
      survival112_the_end: true
      moblottery: true
      skeeter_nether: true
      newcity: true
      elytralobby: false
      skywarslobby: true
      parkourmedium: false
      formuladrift: false
      speedforce: true
      fortressofsolitude: true
      runner: true
      turfwars: true
      hurdles: false
      crossfire: true
      metropolis: true
      longparkour: false
      mazerunner: true
      spleef: false
      parkourhub: false
      towerparkour: false
      boatrace: false
      pvpworldsforest: true
      escaperoom: false
      hurdles2: true
      lavahop: false
      freezetag: true
      minecraftparkourmode: true
      elytrapole: true
      pvpworldsundergroundarmory: true
      obstaclecourse: false
      policeoffice: true
      wooftywoo: false
      parkoureasy: false
      vampirez: true
      superherocity: true
      hilariousrace: false
      pvpparkour: true
      titanstower: true
      straightlineparkour: false
      waynemanor: true
      parkourhard: false
      colosseumlobby: false
      garbageworld: true
      splegg: true
      torture: true
      deathrun: true
      deathmachine: true
      waterprison: false
      flyingbattlearena: false
      sprintparkour: true
      greenfield_the_end: true
      rollercoaster: true
      rules: true
      office: true
      parksideprisonescape: true
      fightclub: true
      pvpworldsruins: true
      flyingbattlelobby: false
      elytraeasy: false
      gotham: true
      megaparkour: false
      info: true
      godlyparkour: false
      chess: false
      hallofjustice: true
      marathon: false
      techcombatknockbackgame: true
      anarchy: true
      infectiontag: true
      elytrahard: false
      verticalparkour: true
      extremesumo: true
      newminigamehub: false
      skeeter_the_end: true
      checkers: false
      quickparkour: true
      flappybirdparkour: false
      deathdrop: false
      skywars: true
      heroicparkour: true
      lasertag: true
      initiation: true
      alpha: true
      pvpparkourlobby: true
      infiniteparkour: false
      turbotowers: false
      colosseum: true
      soccer: true
      greenfield: true
      spleeflobby: false
      utopia: true
      wallenpole: false
      kingoftheladder: true
      anarchy_nether: true
      skeeter: true
      elytramedium: false
      elytrapvp: true
      shortparkour: false
      plots: false
      overvoid: false
      spawn: false
      powerpicker: true
      temple: true
      labyrinth: true
      pvpworldslobby: true
      infinitycity: true
    ProtectFreshSpawns: true
    PunishLogout: true
    CombatTimeoutSeconds: 15
    AllowCombatItemDrop: false
    BlockedSlashCommands: /home;/vanish;/spawn;/tpa
    ProtectPlayersInLandClaims:
      PlayerOwnedClaims: true
      AdministrativeClaims: true
      AdministrativeSubdivisions: true
    AllowLavaDumpingNearOtherPlayers: true
    AllowFlintAndSteelNearOtherPlayers: true
    ProtectPetsOutsideLandClaims: false
  Economy:
    ClaimBlocksPurchaseCost: 0.0
    ClaimBlocksSellValue: 0.0
  ProtectItemsDroppedOnDeath:
    PvPWorlds: false
    NonPvPWorlds: true
  BlockLandClaimExplosions: true
  BlockSurfaceCreeperExplosions: true
  BlockSurfaceOtherExplosions: true
  LimitSkyTrees: true
  LimitTreeGrowth: false
  LimitPistonsToLandClaims: true
  FireSpreads: false
  FireDestroys: false
  AdminsGetWhispers: true
  AdminsGetSignNotifications: true
  SmartBan: true
  Mute New Players Using Banned Words: true
  MaxPlayersPerIpAddress: 3
  Siege:
    Worlds: []
    BreakableBlocks:
    - DIRT
    - GRASS
    - LONG_GRASS
    - COBBLESTONE
    - GRAVEL
    - SAND
    - GLASS
    - THIN_GLASS
    - WOOD
    - WOOL
    - SNOW
  EndermenMoveBlocks: false
  SilverfishBreakBlocks: false
  CreaturesTrampleCrops: false
  RabbitsEatCrops: true
  HardModeZombiesBreakDoors: false
  Database:
    URL: ''
    UserName: ''
    Password: ''
  UseBanCommand: false
  BanCommandPattern: ban %name% %reason%
  Mods:
    BlockIdsRequiringAccessTrust: []
    BlockIdsRequiringContainerTrust:
    - 99999:*:Example - ID 99999, all data values.
    BlockIdsExplodable: []
    PlayersIgnoringAllClaims: []
  Abridged Logs:
    Days To Keep: 7
    Included Entry Types:
      Social Activity: true
      Suspicious Activity: true
      Administrative Activity: false
      Debug: false
      Muted Chat Messages: false
